<div style="background-color: #90A8A5; padding: 10px; height: 100px;  position: relative;">
    <div style="font-family: 'Georgia', serif; font-size: 20px; padding: 10px; text-align: right; position: absolute; right: 20px;">
        Trisha <br>
        <span style="font-family: 'Arial', sans-serif;font-size: 12px; color: #0a0a0a;">AI/ML Enthusiast | Data Analyst | Second-Year Engineering Student</span>


<div style="background-color:#232023; padding: 10px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif;">
    Artificial Intelligence/Machine Learning UpSkills Notebook <br> 
    <h3 style="text-align: center; color: white; font-size: 15px; font-family: 'Arial', sans-serif;">From Basics to Real-World — Starts Your ML Journey</h3></div>

# 📘  Agenda NumPy Basics — Day 
1. Random Number Generation
2. Boolean Masking & Filtering
3. Axis in NumPy
4. Broadcasting
5. Basic Statistical Functions
---

## 1️⃣0️⃣  Random Number Generation
Random numbers are used in machine learning for:
- Weight initialization
- Data shuffling
- Sampling
- Simulations

NumPy provides random number generation using `numpy.random`.

In [1]:
import numpy as np

In [17]:
# Random float number between 0 and 1
print(np.random.rand())

0.9452713752137186


In [15]:
# Random 5 floats between 0 and 1
print(np.random.rand(5))

[0.52229157 0.39923703 0.82973324 0.35552743 0.82995135]


In [16]:
# Random floats for the 2D Matrix of size = 2,3
print(np.random.rand(2, 3))

[[0.12491324 0.47242923 0.4617406 ]
 [0.90380251 0.27796391 0.50743391]]


In [18]:
# Random integers
print(np.random.randint(1, 10)) # between 1 and 10
print(np.random.randint(1, 10, size=5))  # 1D Array
print(np.random.randint(1, 10, size=(2, 3)))  # 2D Array of size = 2,3

7
[7 3 9 2 5]
[[9 3 2]
 [8 3 1]]


In [19]:
# Setting random seed
np.random.seed(42)
print(np.random.rand(3))


[0.37454012 0.95071431 0.73199394]


---

## 1️⃣1️⃣ Boolean Masking & Filtering
Boolean masking is used to filter data based on conditions.
It creates a boolean (True/False) array and selects values where the condition is True.

This is heavily used in:
- Data cleaning
- Feature selection
- Conditional filtering in ML

In [38]:
arr = np.array([10, 20, 30, 40, 50])

print(arr > 25)
print(arr[arr > 25])
print(arr[(arr > 20) & (arr < 50)])


[False False  True  True  True]
[30 40 50]
[30 40]


---

## 1️⃣2️⃣ Axis in NumPy
Axis defines the direction in which an operation is performed.

- `axis = 0` → column-wise operation
- `axis = 1` → row-wise operation

Axis is one of the most important and confusing concepts in NumPy.

In [22]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])

print(np.sum(matrix, axis=0))  # column-wise

[5 7 9]


In [21]:
print(np.sum(matrix, axis=1))  # row-wise

[ 6 15]


In [25]:
print(np.mean(matrix, axis=0))

[2.5 3.5 4.5]


In [26]:
print(np.mean(matrix, axis=1))

[2. 5.]


In [27]:
print(np.max(matrix, axis=0))

[4 5 6]


In [28]:
print(np.min(matrix, axis=1))

[1 4]


---

## 1️⃣3️⃣ Broadcasting
- Broadcasting allows NumPy to perform operations on arrays of different shapes.

- The smaller array is automatically expanded to match the shape of the larger array.

- Broadcasting removes the need for loops and makes computation faster.

In [23]:
arr1 = np.array([1, 2, 3])
print(arr1 + 10)

matrix2 = np.array([[1, 2],
                     [3, 4]])

print(matrix2 + np.array([10, 20]))

[11 12 13]
[[11 22]
 [13 24]]


In [30]:
# Scalar broadcasting
arr = np.array([1, 2, 3, 4])
print(arr * 5)

[ 5 10 15 20]


In [31]:
# Row-wise broadcasting
mat = np.array([[1, 2, 3],
                [4, 5, 6]])

print(mat + np.array([10, 20, 30]))

[[11 22 33]
 [14 25 36]]


In [32]:
# Column-wise broadcasting
print(mat + np.array([[100], [200]]))

[[101 102 103]
 [204 205 206]]


In [33]:
# Reshape and Broad-Casting together
data = np.arange(1, 13)
data = data.reshape(3, 4)
print(data)

print(data + np.array([1, 2, 3, 4]))


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 2  4  6  8]
 [ 6  8 10 12]
 [10 12 14 16]]


---

## 1️⃣4️⃣ Basic Statistical Functions
NumPy provides built-in statistical functions such as:
- Mean
- Median
- Variance
- Standard Deviation

These functions are widely used in data analysis and machine learning.

In [24]:
data = np.array([10, 20, 30, 40])

print(np.mean(data))
print(np.median(data))
print(np.var(data))
print(np.std(data))

25.0
25.0
125.0
11.180339887498949


In [34]:
# Stats along axis
marks = np.array([[70, 80, 90],
                  [60, 75, 85],
                  [88, 92, 95]])

print(np.mean(marks, axis=0))
print(np.mean(marks, axis=1))

[72.66666667 82.33333333 90.        ]
[80.         73.33333333 91.66666667]


In [37]:
# Feature matrix (X) and labels (y)
X = np.array([[1, 2],
              [2, 3],
              [3, 4],
              [4, 5]])

y = np.array([0, 0, 1, 1])
# Normalize features
X_norm = (X - np.mean(X, axis=0)) / np.std(X, axis=0)
print(X_norm)

# Filter samples
print(X[y == 1])


[[-1.34164079 -1.34164079]
 [-0.4472136  -0.4472136 ]
 [ 0.4472136   0.4472136 ]
 [ 1.34164079  1.34164079]]
[[3 4]
 [4 5]]


---

## 15. Day 2 Summary
- Learned random number generation
- Understood boolean masking
- Studied axis concept
- Introduced broadcasting
- Used basic statistical functions