<div style="background-color: #90A8A5; padding: 10px; height: 100px;  position: relative;">
    <div style="font-family: 'Georgia', serif; font-size: 20px; padding: 10px; text-align: right; position: absolute; right: 20px;">
        Trisha <br>
        <span style="font-family: 'Arial', sans-serif;font-size: 12px; color: #0a0a0a;">AI/ML Enthusiast | Data Analyst | Second-Year Engineering Student</span>


<div style="background-color:#232023; padding: 10px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif;">
    Artificial Intelligence/Machine Learning UpSkills Notebook <br> 
    <h3 style="text-align: center; color: white; font-size: 15px; font-family: 'Arial', sans-serif;">From Basics to Real-World — Starts Your ML Journey</h3></div>

# 📘 NumPy Learning Agenda (Beginner → Intermediate)

1. Introduction to NumPy  
2. Installing & Importing NumPy  
3. Creating 1D & 2D Arrays  
4. Array Properties (`ndim`, `shape`, `dtype`)  
5. Special Arrays (`zeros`, `ones`, `arange`, `linspace`)  
6. Indexing & Slicing  
7. Mathematical Operations  
8. Built-in Functions (`sum`, `mean`, `max`)  
9. Reshaping Arrays  




## 1️⃣ Introduction to NumPy
- What is NumPy?
- Why NumPy is faster than Python lists
- Importance of NumPy in AI / ML / Data Science

---


NumPy = Numerical Python
It is used for:

- Fast mathematical operations

- Working with arrays, matrices

- Backbone of Data Science, AI, ML, Deep Learning

👉 Python lists are slow for numbers. NumPy arrays are very fast.

---
## 2️⃣ Installing & Importing NumPy
- Installing NumPy
- Importing NumPy using `import numpy as np`

In [43]:
# !pip install numpy
import numpy as np

---
## 3️⃣ Creating NumPy Arrays
- Creating 1D arrays
- Creating 2D arrays (matrices)


In [6]:
# From Python List
# 1-D Array
arr = np.array([1,2,3,4,5,6])
print(arr)

[1 2 3 4 5 6]


In [7]:
# 2-D Array(Matrix)
matrix = np.array([[2,3,4],
                   [5,6,7]])
print(matrix)

[[2 3 4]
 [5 6 7]]


---

## 4️⃣ Array Properties
- `ndim` (number of dimensions)
- `shape` (rows, columns)
- `size` (total elements)
- `dtype` (data type)

In [8]:
print(arr.ndim)  # dimensions

1


In [9]:
print(arr.shape) # shape

(6,)


In [11]:
print(arr.size)  # size

6


In [12]:
print(arr.dtype) # data-type

int64


---

## 5️⃣ Creating Special Arrays
- Arrays of zeros (`np.zeros`)
- Arrays of ones (`np.ones`)
- Range-based arrays (`np.arange`)
- Evenly spaced values (`np.linspace`)

In [14]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [15]:
np.zeros(8)

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [17]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

### Range ###

In [44]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(2,20,3)

array([ 2,  5,  8, 11, 14, 17])

### Evenly Spaced Values ###

In [20]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

---

## 6️⃣ Indexing and Slicing
- Accessing elements using index
- Negative indexing
- Slicing arrays


In [21]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr[0])

1


In [45]:
print(arr[-4])

3


In [22]:
print(arr[:])

[1 2 3 4 5 6 7 8]


In [23]:
print(arr[5:9])

[6 7 8]


In [25]:
print(arr[-6: -2])

[3 4 5 6]


---

## 7️⃣ Mathematical Operations
- Element-wise addition
- Subtraction
- Multiplication
- Division
- Power operations

In [26]:
a = np.array([4,7,3,5,9])
b = np.array([2,6,8,3,1])
print(a,b)

[4 7 3 5 9] [2 6 8 3 1]


In [27]:
print(a+b)

[ 6 13 11  8 10]


In [28]:
print(a-b)

[ 2  1 -5  2  8]


In [29]:
print(a*b)

[ 8 42 24 15  9]


In [31]:
print(a//b)

[2 1 0 1 9]


In [46]:
print(a**2)

[16 49  9 25 81]


---

## 8️⃣ NumPy Built-in Functions
- `sum()`
- `mean()`
- `max()` and `min()`
- `std()` (standard deviation)


In [35]:
print(arr)
print(np.sum(arr))


[1 2 3 4 5 6 7 8]
36


In [34]:
print(np.max(arr))

8


In [36]:
print(np.min(arr))

1


In [38]:
print(np.mean(arr))

4.5


In [39]:
print(np.std(arr))

2.29128784747792


---
## 9️⃣ Reshaping Arrays
- Using `reshape()`
- Converting 1D arrays to 2D arrays
- Understanding shape compatibility

In [42]:
arr = np.arange(1,7)
print(arr)
print(arr.reshape(2,3))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


<div style="background-color: #C3DEDD; padding: 10px; height: 100px; border-radius: 15px; position: relative;">
    <div style="font-family: 'Georgia', serif; font-size: 20px; padding: 10px; text-align: right; position: absolute; right: 20px;">
        Trisha Dhiman <br>
        <span style="font-family: 'Arial', sans-serif;font-size: 12px; color: #0a0a0a;">AI/ML Enthusiast | Data Analyst | Second-Year Engineering Student</span>
    </div>
    <div style="font-family: Arial, sans-serif; font-size: 14px; line-height: 1.6;">
    <strong>📞 Connect @</strong><br>
    📧 Mail (Trisha Dhiman): <a href="mailto:dhimantrisha1812@gmail.com">dhimantrisha1812@gmail.com</a><br>
    📞 Contact: <a href="tel:+91-9729832340">+91-9729832340</a><br>
</div>
</div>

<br>

