<div style="background-color: #90A8A5; padding: 10px; height: 100px;  position: relative;">
    <div style="font-family: 'Georgia', serif; font-size: 20px; padding: 10px; text-align: right; position: absolute; right: 20px;">
        Trisha <br>
        <span style="font-family: 'Arial', sans-serif;font-size: 12px; color: #0a0a0a;">AI/ML Enthusiast | Data Analyst | Second-Year Engineering Student</span>



<div style="background-color:#232023; padding: 10px; text-align: center; color: white; font-size: 32px; font-family: 'Arial', sans-serif;">
    Artificial Intelligence/Machine Learning UpSkills Notebook <br> 
    <h3 style="text-align: center; color: white; font-size: 15px; font-family: 'Arial', sans-serif;">From Basics to Real-World — Starts Your ML Journey</h3></div>

# NumPy — Day 3 (Matrix Operations & Linear Algebra Basics)

## 16. Matrix Multiplication
Matrix multiplication is different from element-wise multiplication.
It is the core operation used in machine learning and deep learning models.

NumPy provides multiple ways to perform matrix multiplication.

In [2]:
import numpy as np

In [3]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A * B)      # Element-wise multiplication
print(A @ B)      # Matrix multiplication
print(np.dot(A, B))


[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


---

## 17. Dot Product
The dot product is used to multiply matrices and vectors.
It is widely used in linear regression and neural networks.

In [4]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])

print(np.dot(v1, v2))


32


---

## 18. Transpose of a Matrix
Transpose converts rows into columns and columns into rows.
It is commonly used to align matrix dimensions for multiplication.

In [5]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])

print(M.T)


[[1 4]
 [2 5]
 [3 6]]


---

## 19. Identity Matrix
An identity matrix is a square matrix with:
- 1s on the diagonal
- 0s elsewhere

It behaves like the number 1 in matrix multiplication.

In [6]:
I = np.eye(3)
print(I)

print(A @ I[:2, :2])   # Identity effect



[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 2.]
 [3. 4.]]


---

## 20. Inverse of a Matrix
The inverse of a matrix is used to solve linear equations.
Not all matrices have an inverse.

In [7]:
C = np.array([[4, 7],
              [2, 6]])

C_inv = np.linalg.inv(C)
print(C_inv)

print(C @ C_inv)   # Should be close to identity

[[ 0.6 -0.7]
 [-0.2  0.4]]
[[ 1.00000000e+00  0.00000000e+00]
 [-2.22044605e-16  1.00000000e+00]]


---

## 21. Stacking Arrays
Stacking is used to combine multiple arrays into one.
NumPy supports vertical and horizontal stacking.

In [8]:
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])

print(np.hstack((x, y)))
print(np.vstack((x, y)))


[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


---

## 22. Sorting and Searching
NumPy provides efficient functions for:
- Sorting data
- Finding indices
- Applying conditions

In [9]:
data = np.array([40, 10, 30, 20])

print(np.sort(data))
print(np.argsort(data))
print(np.where(data > 25))

[10 20 30 40]
[1 3 2 0]
(array([0, 2]),)


---

##  Summary
- Learned matrix multiplication
- Used dot product
- Understood transpose
- Introduced linear algebra concepts
- Practiced stacking, sorting, and searching

<div style="background-color: #C3DEDD; padding: 10px; height: 100px; border-radius: 15px; position: relative;">
    <div style="font-family: 'Georgia', serif; font-size: 20px; padding: 10px; text-align: right; position: absolute; right: 20px;">
        Trisha Dhiman <br>
        <span style="font-family: 'Arial', sans-serif;font-size: 12px; color: #0a0a0a;">AI/ML Enthusiast | Data Analyst | Second-Year Engineering Student</span>
    </div>
    <div style="font-family: Arial, sans-serif; font-size: 14px; line-height: 1.6;">
    <strong>📞 Connect @</strong><br>
    📧 Mail (Trisha Dhiman): <a href="mailto:dhimantrisha1812@gmail.com">dhimantrisha1812@gmail.com</a><br>
    📞 Contact: <a href="tel:+91-9729832340">+91-9729832340</a><br>
</div>
</div>

<br>

